
version: '3.8'
services:

  app:
    build: ./django_rag_service
    container_name: "rag-ai-app"
    restart: always
    # command: "tail -f /dev/null"
    volumes:
      - .:/application
    user: appuser
    depends_on:
      - database
    ports:
      - "8000:8000"
      - "5000:5000"
    env_file:
      - ./django_rag_service/config/.env

  fe-angular-app:
    container_name: "angulr-ui-app"
    build:
      context: ./frontend/dash-app  # Set the context to the directory containing Angular code
      dockerfile: Dockerfile        # Dockerfile is inside the context directory
    ports:
      - "4200:4200"                 # Replace with your Angular app's port
    volumes:
      - ./frontend/dash-app:/app    # Optional, for live reloading during development


  database:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres_data:
    driver: local

networks:
  pgnetwork:
    driver: bridge