
version: '3.8'
services:

  app:
    build: ./django_rag_service
    container_name: "rag-ai-app"
    restart: always
    # command: "tail -f /dev/null"
    volumes:
      - .:/application
    user: appuser
    depends_on:
      - database
    ports:
      - "8000:8000"
      - "5000:5000"
    env_file:
      - ./django_rag_service/config/.env

  angular-app:
    build: ./frontend
    ports:
      - "80:80"


  database:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres_data:
    driver: local

networks:
  pgnetwork:
    driver: bridge