
version: '3.8'
services:

  app:
    build: ./django_rag_service
    container_name: "rag-ai-app"
    restart: always
    # command: "tail -f /dev/null"
    volumes:
      - .:/application
    user: appuser
    depends_on:
      - pgvector_db
    ports:
      - "8000:8000"
      - "5000:5000"
    env_file:
      - ./django_rag_service/config/.env

  fe-angular-app:
    container_name: "angulr-ui-app"
    build:
      context: ./frontend/dash-app  # Set the context to the directory containing Angular code
      dockerfile: Dockerfile        # Dockerfile is inside the context directory
    ports:
      - "4200:4200"                 # Replace with your Angular app's port
    volumes:
      - ./frontend/dash-app:/app    # Optional, for live reloading during development


  pgvector_db:
    image: pgvector/pgvector:pg17
    container_name: "rag-postgres-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data
      - .:/application
    restart: always


volumes:
  psql-data:
    driver: local

# networks:
#   pgnetwork:
#     driver: bridge